### PR TITLE
If role is not provided, use default role.

### PR DESCRIPTION
**Pull request by felixfriedrich**
Because of https://github.com/cloudfoundry/cli/issues/1173 this pull request sets 'owner' as the default role if no role is specified in the bind-service command.

I guess reading the default role from the config would be great, but I would need some advice how to implement that.

If you don't want to merge it as is, please provide advice on how to improve the code.

Thanks!

### CODE REVIEW

**Comment by felixfriedrich** [comment]
I changed the role from 'owner' to 'storage.objectAdmin'. (I assued owner, means owner of the bucket.) Yet, the role is applied the complete project, not just to the bucket, which would be better.

**Comment by ccemeraldeyes** [comment]
I'd like to see roles default to minimum permissions (with user-provided overrides, a feature that is coming as soon as a large-scale refactor is done), and I'd like it to see it set up for every service. The issue for that is https://github.com/GoogleCloudPlatform/gcp-service-broker/issues/9

Is this a blocker for you? How urgent?

**Comment by felixfriedrich** [comment]
In a case where the minimum permissions would not be good enough and the user provided override is provided via `-c {"role": "overrrideRole"}` the solution you outlined would not solve my problem as arguments to the bind command are not possible in the manifest (see: https://github.com/cloudfoundry/cli/issues/1173).

I'd suggest putting the default in the config of service broker, in the service definition?

Does that make sense? Or did I misunderstand you?

**Comment by felixfriedrich** [comment]
I signed the CLA by the way.

**Comment by ccemeraldeyes** [comment]
> I'd suggest putting the default in the config of service broker, in the service definition?

Yes, that's coming. I'd *estimate* 1 month to delivery. Can you wait that long? Or is this a more urgent blocker than that?

**Comment by felixfriedrich** [comment]
That sounds great, @ccemeraldeyes ! I can wait since the small change in this pull request unblocks me for now. Thanks for helping, I am going to close the pull request.

Best regards from Berlin, Germany,

Felix

**Comment by felixfriedrich** [comment]
One last question though: The roles being specified will they be only applied to the bucket or to the project (as it is at the moment AFAIK)? Should this maybe be configurable as well?

**Comment by ccemeraldeyes** [comment]
It should only apply to the bucket. There's a ticket for that as well that's high priority.

**Comment by felixfriedrich** [comment]
Thanks, I am quite excited about all the changes :-) Thank you!

**Pull request closed without merging**
