### PR TITLE
Fix #137: Add Datastore support

### LINKED ISSUE #137: Add Cloud Datastore
Datastore seems like a nice idea to have.  I haven't had any requests for it, but since it appears to resemble Bigtable, but doesn't require you to allocate a minimum of three nodes, it'd be quite a bit more economical.

### PR DESCRIPTION
**Pull request by athieriot**
Based largely on @johnsonj work around Stackdriver brokers. Like them, no actual service is created.

Validation:

Deployed service broker, created instances, bound to an app. Verified the service account in the ENV had appropriate access
Some light integration testing

### CODE REVIEW

**Comment by athieriot** [comment]
I signed it!

**Comment by ccemeraldeyes** [comment]
Thanks for your PR! Looks great!

**Comment by athieriot** [comment]
Thank you ! :)

I hope those test values are fine (Number of services). I was hoping some CI would run with the Pull Requests.

**Comment by ccemeraldeyes** [comment]
CI runs when I merge to master. Were you able to run go test alright, though? I need to add some docs for integration tests, but hopefully unit tests were easy enough?

**Pull request merged**
